const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("orca", {
  ps: () => ipcRenderer.invoke("orca:ps"),
  terminals: () => ipcRenderer.invoke("orca:terminals"),
  rateLimits: () => ipcRenderer.invoke("orca:rate-limits"),
  worktrees: () => ipcRenderer.invoke("orca:worktrees"),
  terminalRead: (handle, screen, cursor, limit) => ipcRenderer.invoke("orca:terminal-read", handle, screen, cursor, limit),
  terminalSend: (handle, text, enter, waitSubmit) => ipcRenderer.invoke("orca:terminal-send", handle, text, enter, waitSubmit),
  terminalWait: (handle, condition, timeoutMs) => ipcRenderer.invoke("orca:terminal-wait", handle, condition, timeoutMs),
  terminalInterrupt: (handle) => ipcRenderer.invoke("orca:terminal-interrupt", handle),
  terminalClose: (handle) => ipcRenderer.invoke("orca:terminal-close", handle),
  terminalSwitch: (handle) => ipcRenderer.invoke("orca:terminal-switch", handle),
  worktreeCreate: (opts) => ipcRenderer.invoke("orca:worktree-create", opts),
  worktreeRm: (id) => ipcRenderer.invoke("orca:worktree-rm", id),
  openPath: (p) => ipcRenderer.invoke("orca:open-path", p),
  notify: (title, body) => ipcRenderer.invoke("orca:notify", title, body),
  toggleAlwaysOnTop: () => ipcRenderer.invoke("orca:toggle-always-on-top"),
  sendSessionCounts: (counts) => ipcRenderer.send("orca:session-counts", counts),
  resizeWindow: (w, h, forceHeight) => ipcRenderer.send("orca:resize-window", w, h, forceHeight),
  claudeSessions: (filters) => ipcRenderer.invoke("orca:claude-sessions", filters),
  claudeSessionDetail: (id) => ipcRenderer.invoke("orca:claude-session-detail", id),
  orchRuns: () => ipcRenderer.invoke("orca:orch-runs"),
  orchTasks: (runId) => ipcRenderer.invoke("orca:orch-tasks", runId),
  orchWorkers: () => ipcRenderer.invoke("orca:orch-workers"),
  orchDispatch: (taskId, handle) => ipcRenderer.invoke("orca:orch-dispatch", taskId, handle),
  orchTaskCreate: (spec, runId) => ipcRenderer.invoke("orca:orch-task-create", spec, runId),
  orchSendToTerminal: (handle, text) => ipcRenderer.invoke("orca:orch-send", handle, text),
  clipboardRead: () => ipcRenderer.invoke("orca:clipboard-read"),
  clipboardWrite: (text) => ipcRenderer.invoke("orca:clipboard-write", text),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  setOpacity: (val) => ipcRenderer.send("orca:set-opacity", val),
  scanPorts: () => ipcRenderer.invoke("orca:scan-ports"),
  killProcess: (pid) => ipcRenderer.invoke("orca:kill-process", pid),
});
